name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    uses: compliance-framework/workflows/.github/workflows/release-go-image.yml@5a81b1ac6081babf702713afb497d5a4f5c662bf # v1.0.0
    with:
      images: '[{"name":"mock-api","dockerfile":"Dockerfile","context":"."}]'
    permissions:
      contents: read
      packages: write
    secrets: inherit
