name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    uses: compliance-framework/workflows/.github/workflows/release-go-image.yml@ec58cea2c02f12b5dad6b23a7bfdc84360f59f11 # v1.3.0
    with:
      images: '[{"name":"mock-api","dockerfile":"Dockerfile","context":"."}]'
    permissions:
      contents: read
      packages: write
    secrets: inherit
